/**
 * Created by yogprakash on 6/5/17.
 */

export const TEKION_GET_GRAPH_CONFIG_REQUEST = "TEKION_GET_GRAPH_CONFIG_REQUEST";
export const TEKION_GET_GRAPH_CONFIG_SUCCESS = "TEKION_GET_GRAPH_CONFIG_SUCCESS";
export const TEKION_GET_GRAPH_CONFIG_FAILURE = "TEKION_GET_GRAPH_CONFIG_FAILURE";

// export const TEKION_SET_GRAPH_CONFIG_REQUEST = "TEKION_SET_GRAPH_CONFIG_REQUEST";
// export const TEKION_SET_GRAPH_CONFIG_SUCCESS = "TEKION_SET_GRAPH_CONFIG_SUCCESS";
export const TEKION_SET_GRAPH_CONFIG = "TEKION_SET_GRAPH_CONFIG";
